name: Deploy WordPress Theme

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: web0171.zxcs-klant.nl
          username: admin@u221352p487803.web0171.zxcs-klant.nl
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: /domains/u221352p487803.web0171.zxcs-klant.nl/public_html/wp-content/themes/leadsprint-child/
